version: 0.2
phases:
  pre_build:
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR/"
      - cd $CODEBUILD_SRC_DIR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_URL
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $CONTAINER_NAME .
      - docker tag $REPO_NAME $IMAGE_URL/$REPO_NAME
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image..
      - docker push $IMAGE_URL/$REPO_NAME
      - echo "imagedefinitions.json > [{\"name\":\"$CONTAINER_NAME\",\"imageUri\":\"$IMAGE_URL/$REPO_NAME\"}]" > imagedefinitions.json
      - printf '[{"name":"%s","imageUri":"%s/%s"}]' "$CONTAINER_NAME" "$IMAGE_URL" "$REPO_NAME" > imagedefinitions.json
env:
  variables:
    AWS_ACCOUNT_ID: 886436929815
    AWS_DEFAULT_REGION: ap-southeast-1
    CONTAINER_NAME: skin-segment-app
    IMAGE_URL: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    REPO_NAME: skin-segment-app:latest
artifacts:
  base-directory: $CODEBUILD_SRC_DIR
  files:
    - imagedefinitions.json
    - appspec.yml
    - scripts/start_app.sh
    - scripts/stop_app.sh
  discard-paths: no
  name: '.'