version: 0.0
phases:
  pre_build:
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR/"
      - cd $CODEBUILD_SRC_DIR
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 886436929815.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t skin-segment-app:latest .
      - docker tag skin-segment-app:latest 886436929815.dkr.ecr.ap-southeast-1.amazonaws.com/skin-segment-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image..
      - docker push 886436929815.dkr.ecr.ap-southeast-1.amazonaws.com/skin-segment-app:latest
      - cd $CODEBUILD_SRC_DIR
      - echo "imagedefinitions.json > [{\"name\":\"skin-segment-app\",\"imageUri\":\"886436929815.dkr.ecr.ap-southeast-1.amazonaws.com/skin-segment-app:latest\"}]" > imagedefinitions.json
      - printf "[{\"name\":\"skin-segment-app\",\"imageUri\":\"886436929815.dkr.ecr.ap-southeast-1.amazonaws.com/skin-segment-app:latest\"}]" > imagedefinitions.json
env:
  variables:
    AWS_ACCOUNT_ID: 886436929815
    AWS_DEFAULT_REGION: ap-southeast-1
    CONTAINER_NAME: skin-segment-app
    IMAGE_URL: 886436929815.dkr.ecr.ap-southeast-1.amazonaws.com
    REPO_NAME: skin-segment-app:latest
artifacts:
  base-directory: $CODEBUILD_SRC_DIR
  files:
    - imagedefinitions.json
    - appspec.yml
    - scripts/start_app.sh
    - scripts/stop_app.sh
  discard-paths: no
  name: '.'